# Generated by Django 5.2.8 on 2025-11-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PHQ9', 'PHQ-9 Depression'), ('GAD7', 'GAD-7 Anxiety')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('response', models.IntegerField()),
            ],
        ),
    ]
