# Generated by Django 5.2.8 on 2025-11-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('HELPLINE', 'Helpline'), ('TIP', 'Self-Help Tip'), ('PROFESSIONAL', 'Professional Service'), ('CRISIS', 'Crisis Support')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('severity_min', models.IntegerField(default=0)),
                ('severity_max', models.IntegerField(default=27)),
            ],
        ),
    ]
